name: Builds

on:
  push:

env:
  GFORTRAN_PATH: "/usr/local/lib/gcc/11"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Build javaHeclib
        run: |
          sudo ln -s /usr/local/bin/gfortran-11 /usr/local/bin/gfortran
          cd ${{ github.workspace }}/heclib
          make

  test:
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11]
    runs-on: ${{ matrix.os }}
    if: startsWith(matrix.os, 'ubuntu')
    steps:
      - uses: actions/checkout@v2

      - name: Checkout tools repo
        uses: actions/checkout@v2
        with:
          repository: HydrologicEngineeringCenter/dss-test-data
          path: dss-test-data

      - name: build main library
        run: |
          cd heclib
          make

      - name: build and run basic C test programs
        run: |
          cd test/C
          ./unix_test

      - name: build and run Dss-C test program
        run: |
          cd test/Dss-C
          make test

      - name: build and run Fortran test program
        run: |
          cd test/Fortran
          make test
