name: macOS
on: [workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Checkout tools repo
        uses: actions/checkout@v2
        with:
          repository: HydrologicEngineeringCenter/dss-test-data
          path: dss-test-data

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
                      
      - name: build main library
        run: |
          cd heclib
          make
          
