name: Release

on:
  push:
    tags:
      - "[0-9]+-[A-Z]+-[0-9]+"

env:
  GFORTRAN_PATH: "/usr/local/lib/gcc/11"

jobs:
  library-Build:
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11]
    if: endsWith(github.ref, 'master')
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build javaHeclib
        run: |
          sudo ln -s /usr/local/bin/gfortran-11 /usr/local/bin/gfortran
          cd ${{ github.workspace }}/heclib
          make

      - name: Archive Zip
        run: |
          cd ${{ github.workspace }}/heclib/javaHeclib/Output
          tar -czf ${{ github.workspace }}/heclib/javaHeclib_${{ matrix.os }}_${{ github.ref_name }}.tar.gz --exclude="src" .

      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "${{ github.workspace }}/heclib/javaHeclib_${{ matrix.os }}_${{ github.ref_name }}*"
          bodyFile: ${{ github.workspace }}/RELEASE.md
          makeLatest: true
